### ISSUE TITLE
The main branch should be named master

### ISSUE THREAD

**Issue by sbidoul** [shopinvader/shopinvader-template#6]
Hi,

I'd like to suggest renaming the main branch of the shopinvader template to `master` instead of `10.0`.

Indeed, 10.0 conveys the idea that it is linked to Odoo 10. This may be true today, but we must strive to have Odoo REST services that are stable across versions, so we can migrate Odoo independently of the shop front end, keeping coupling loose.

**Comment by sebastienbeau** [comment]
This have been done
