### ISSUE TITLE
Error with launching with docker-compose

### ISSUE THREAD

**Issue by quentinDupont** [shopinvader/shopinvader-template#8]
Here the error I get on my browser when launching the shopinvader template with this command : 
`docker-compose run --service-ports wagon gosu ubuntu bash`

    Erreur avec docker compose :

    Liquid error: Extending a missing page. Page/Layout with fullpath 'layouts/simple' was not found
    File:

    /workspace/app/views/pages/index.liquid
    Code

                

    Backtrace

    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/liquid/tags/extends.rb:20:in `parse_parent_template'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/extends.rb:30:in `parse'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
    /usr/local/bundle/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/liquid/template.rb:24:in `parse'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/services/liquid_parser_service.rb:26:in `_parse'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/services/liquid_parser_service.rb:9:in `parse'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/renderer.rb:39:in `parse_and_render_liquid'
    /usr/local/bundle/bundler/gems/locomotive_shopinvader-5e9d9d861d50/lib/shop_invader/middlewares/renderer.rb:11:in `parse_and_render_liquid'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/path.rb:13:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/redirection.rb:15:in `_call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
    /usr/local/bundle/gems/i18n-1.1.0/lib/i18n.rb:284:in `with_locale'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
    /usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/core_ext/time/zones.rb:64:in `use_zone'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:49:in `_call'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:37:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
    /usr/local/bundle/bundler/gems/wagon-ebcc4cf08cdc/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
    /usr/local/bundle/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:23:in `_call'
    /usr/local/bundle/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:14:in `call'
    /usr/local/bundle/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/dynamic_assets.rb:22:in `call'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/static.rb:149:in `call'
    /usr/local/bundle/bundler/gems/steam-a4d95ab21a10/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
    /usr/local/bundle/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
    /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:153:in `call'
    /usr/local/bundle/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
    /usr/local/bundle/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
    /usr/local/bundle/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
    /usr/local/bundle/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
    /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'`

I manage to make it work with locomotive [tutorial](https://locomotive-v3.readme.io/docs/quick-start) and this command `bundle exec wagon serve `

**Comment by sebastienbeau** [comment]
New doc available here: https://doc.shopinvader.com
The issue have been fixed
